- name: Download Istio CLI
  shell: wget https://github.com/istio/istio/releases/download/1.2.0/istio-1.2.0-linux.tar.gz 
  warn: false
  args:
    chdir: /tmp
    creates: istio-download.log

- name: Compact Istio CLI
  shell: tar xvf istio-1.2.0-linux.tar.gz
  args:
    chdir: /tmp
    creates: istio-tar.log

- name: Move istioctl to PATH
  shell: cp istio-1.2.0/bin/istioctl /usr/local/bin/
  args:
    chdir: /tmp
    creates: istio-path.log

- name: Verify istioctl installation
  shell: istioctl verify-install
  args:
    chdir: /tmp
    creates: istio-verify.log

- name: istioctl install
  shell: kubectl apply -f istio-1.2.0/install/kubernetes/istio-demo-auth.yaml
  args:
    chdir: /tmp
    creates: istio-install.log